# Generated by Django 4.2.7 on 2024-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitel', models.CharField(max_length=30)),
                ('taskDescription', models.CharField(max_length=70)),
                ('is_completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
