# Generated by Django 4.2.7 on 2024-02-29 06:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_blog_likes_blog_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favourites',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
